name: Update Google Scholar Data

on:
  workflow_dispatch:

jobs:
  update-scholar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Libraries
        run: pip install scholarly pandas

      - name: Run Scholar Script
        run: python scholar_update.py
      
      - name: Run Scholar Script
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python scholar_update.py
