name: Update Google Scholar Data

on:
  workflow_dispatch:

jobs:
  update-scholar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Libraries
        run: |
          pip install requests

      - name: Run Scholar Script
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python scholar_update.py

      - name: Commit Updated JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add json_data/*.json

          git diff --staged --quiet || git commit -m "Update Scholar Data"

          git push
